### ISSUE TITLE
Many kerning pairs wrongly displayed with zero value

### ISSUE THREAD

**Issue by retypefoundry** [schriftgestalt/kernalytics-rf-ext#2]
Hi there,

I've found another bug: when checking the tables of a 4 masters Glyphs file some pairs are displayed as zero when in reality they have been properly kerned. I can send you the file for your checking.
<img width="786" alt="screen shot 2018-06-14 at 23 56 29" src="https://user-images.githubusercontent.com/9000095/41453242-4bfd8c6e-7075-11e8-842d-10cdf5105d6e.png">

**Comment by schriftgestalt** [comment]
Are you sure that is isn’t an exception pair? Please send the file.

**Comment by retypefoundry** [comment]
File sent.

**Comment by schriftgestalt** [comment]
Have you clicked the UC_Y + egrave pair? As I said the two bold masters have a pair with UC_Y+egrave, the light masters don’t have that pair. It gets the kerning from the UC_Y+ lc_round pair.

**Comment by retypefoundry** [comment]
Yes, I know. But I think the class kerning in the lighter weights should be displayed anyway. isn't possible? There are a lot of situations where you need to compare class kerning against an exception.

**Comment by schriftgestalt** [comment]
No. That is not the point of that tool. It should show that there are different exceptions in the different masters.

**Comment by retypefoundry** [comment]
The point of the tool is to compare the same kerning pair values in every master to detect problems and inconsistencies. It totally makes sense to have exceptions in the heaviest weights and not in the lighter ones. If the class kerning is not displayed, you are led to believe you forgot to kern this pair, which is not the case.

**Comment by schriftgestalt** [comment]
<img width="800" alt="screenshot" src="https://user-images.githubusercontent.com/174660/41509519-2eb62490-7223-11e8-87b2-19f08fe18dfc.png">
The Robofont is doing almost the same thing. It is better in that it is not displaying zero values and I can fix that.

**Comment by retypefoundry** [comment]
Fine
